/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import game.GameFrame;
import utils.Scores;

/**
 *
 * @author gregory
 */
public class GameOver extends javax.swing.JFrame {

    private int _player1Score ;
    private int _player2Score ;

    public GameOver(int player1Score, int player2Score) {
        initComponents();
        _player1Score = player1Score;
        _player2Score = player2Score;
        player1ScoreLabel.setText(String.format("%d pkt", _player1Score));
        player2ScoreLabel.setText(String.format("%d pkt", _player2Score));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scores = new javax.swing.JButton();
        mainMenu = new javax.swing.JButton();
        player1Nick = new javax.swing.JTextField();
        player2Nick = new javax.swing.JTextField();
        player1Label = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        player1ScoreLabel = new javax.swing.JLabel();
        player2ScoreLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Koniec gry!");

        scores.setText("Zapisz");
        scores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoresActionPerformed(evt);
            }
        });

        mainMenu.setText("Menu główne");
        mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuActionPerformed(evt);
            }
        });

        player1Nick.setText("Wpisz nick");
        player1Nick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1NickActionPerformed(evt);
            }
        });

        player2Nick.setText("Wpisz nick");

        player1Label.setText("Gracz 1");

        player2Label.setText("Gracz 2");

        player1ScoreLabel.setText("0");

        player2ScoreLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scores)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(player1Label))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(player2Label))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(player2ScoreLabel)
                            .addGap(51, 51, 51)
                            .addComponent(player2Nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(player1ScoreLabel)
                            .addGap(51, 51, 51)
                            .addComponent(player1Nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(mainMenu, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1Label)
                    .addComponent(player1ScoreLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2Nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2Label)
                    .addComponent(player2ScoreLabel))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scores)
                    .addComponent(mainMenu))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoresActionPerformed
        // TODO add your handling code here:
        Scores scores = new Scores();
        scores.saveResult(player1Nick.getText(), _player1Score);
        scores.saveResult(player2Nick.getText(), _player2Score);
        BestScoresMenu scoresMenu = new BestScoresMenu();
        scoresMenu.refreshResults();
        scoresMenu.show();
        this.scores.setEnabled(false);
        this.player1Nick.setEditable(false);
        this.player2Nick.setEditable(false);

    }//GEN-LAST:event_scoresActionPerformed

    private void player1NickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1NickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player1NickActionPerformed

    private void mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuActionPerformed
        GameFrame.stopGame();
        this.dispose();
    }//GEN-LAST:event_mainMenuActionPerformed

/*
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOver().setVisible(true);
            }
        });
    }
*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mainMenu;
    private javax.swing.JLabel player1Label;
    private javax.swing.JTextField player1Nick;
    private javax.swing.JLabel player1ScoreLabel;
    private javax.swing.JLabel player2Label;
    private javax.swing.JTextField player2Nick;
    private javax.swing.JLabel player2ScoreLabel;
    private javax.swing.JButton scores;
    // End of variables declaration//GEN-END:variables
}
